language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
  - pip install coverage coviolations_app
install:
  - pip install -U .
script:
  - nosetests --with-coverage 2>test_out
after_script:
  - coverage report
  - covio
